server:
  port: 8080

spring:
  application:
    name: lotuas-feign
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com:
      lotuas:
        feign:
          service:
            FeignUserClient: info