server:
  port: 9000

spring:
  application:
    name: lotuas-invoker1
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#lotuas-sp1:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.lotuas.config.MyRibbonRule
