server:
  port: 8080
spring:
  application:
    name: lotuas-samples-mybatis-spring-boot
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  datasource:
    url: jdbc:mysql://47.97.177.132:3306/lotuas?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    ##数据源名称
    name: druidDataSrouce
    ##初始连接数，初始化发生在显示调用init方法，或者第一次getConnection时
    initialSize: 5
    ##最大连接数
    maxActive: 20
    ##最小连接数
    minIdle: 1
    # 配置获取连接等待超时的时间,毫秒单位
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000

    #建议配置为true，不影响性能，并且保证安全性。
    #申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
    testWhileIdle: true
    ##申请连接时，执行validateQuery，检测连接时候有效，会影响性能
    ##归还连接时，执行validateQuery，检测连接时候有效，会影响性能
    testOnBorrow: false
    testOnReturn: false

    ##检验sql，如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会其作用。
    validationQuery: SELECT 1 FROM DUAL

    # 是否开启PSCache，是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
    poolPreparedStatements: false
    maxOpenPreparedStatements: 20

    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: wall,stat
#    filters: stat,wall,log4j

    ##连接属性配置，sql合并功能，慢查询配置
    connectionProperties: druid.stat.mergeSql=true;dr uid.stat.slowSqlMillis=500

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.lotuas.samples.mybatis.domian
logging:
  level:
    com.lotuas: debug
  file: test.log
