MYSQL_HOST: 47.97.177.132
REDIS_HOST: 47.97.177.132
RABBIT_MQ_HOST: 47.97.177.132

server:
  port: 8085

spring:
  application:
    name: lotuas-auth-server
  mvc:
    date-format: yyyy-MM-dd HH:mm:ss
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 1
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    pool:
    max-active: 20
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/lotuas?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      #配置服务中心(可配置多个,用逗号隔开)
      defaultZone: http://localhost:8761/eureka/
